"use client";
import Image from "next/image";
import Link from "next/link";
import mascotSrc from "../mojomascotnbg.png";
const services=[['ust-ast-installation','UST/AST Installation'],['maintenance-repairs','Maintenance & Repairs'],['compliance-testing','Compliance Testing'],['emergency-service','Emergency Service']];
const navLinks=[['About','/about'],['Services','/services'],['Safety','/safety'],['Contact','/contact']];
function MascotIcon(){return <Image src={mascotSrc} alt="Mojo mascot" fill sizes="56px" style={{objectFit:'contain'}} priority />}
function Brand(){return <span className="brand-logo"><span className="brand-icon"><MascotIcon/></span><span className="brand-copy"><span className="brand-word mojo">MOJO</span><span className="brand-word petroleum">PETROLEUM</span></span></span>}
export function Nav(){return <header className="nav"><div className="shell navin"><Link className="brand" href="/"><Brand/></Link><nav className="links" aria-label="Main navigation">{navLinks.map(([name,href])=><Link key={href} href={href}>{name}</Link>)}<Link className="btn primary" href="/schedule-inspection">Request inspection</Link></nav></div></header>}
export function Footer(){return <footer className="footer"><div className="shell footer-grid"><div><Link className="brand" href="/"><Brand/></Link><p>Setting the Standard in Petroleum Services.</p></div><div><h3>Contact</h3><p><a href="tel:+16506516452">(650) 651-6452</a><br/><a href="mailto:info@mojopetroinc.com">info@mojopetroinc.com</a><br/>433 Airport Blvd. #408<br/>Burlingame, CA 94010</p></div><div><h3>Services</h3>{services.slice(0,4).map(([slug,label])=><p key={slug}><Link href={`/services/${slug}`}>{label}</Link></p>)}</div></div><div className="shell"><small>© {new Date().getFullYear()} Mojo Petroleum Services, Inc. All Rights Reserved. <Link href="/privacy-policy">Privacy Policy</Link></small></div></footer>}
export function Cta(){return <section className="dark section"><div className="shell split"><div><p className="eyebrow">Ready when you are</p><h2>Protect your operation before downtime finds you.</h2><p className="lede">Schedule a site inspection with our MOJO team.</p></div><div><Link className="btn primary" href="/schedule-inspection">Schedule inspection →</Link></div></div></section>}
